# Generated by Django 4.2.7 on 2025-11-29 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('specification', models.TextField()),
                ('available', models.BooleanField(default=True)),
                ('pin', models.BigIntegerField(help_text='Unique PIN associated with prescriptions.', unique=True)),
                ('prescription_file', models.BinaryField(blank=True, help_text='The default prescription format/file (bytea/BLOB data).', null=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('revenue', models.BigIntegerField()),
                ('appointments', models.BigIntegerField(help_text='Total number of appointments.')),
                ('availability', models.TextField(help_text="Availability status (e.g., 'Fully Staffed', 'Limited Beds').")),
                ('lab_report_file', models.BinaryField(blank=True, help_text='General lab report file template/example.', null=True)),
                ('doctors', models.ManyToManyField(related_name='hospitals', to='accounts.doctor')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abha_id', models.BigIntegerField(help_text='Unique ABHA ID for the patient.', unique=True)),
                ('name', models.TextField()),
                ('blood_grp', models.TextField()),
                ('age', models.BigIntegerField()),
                ('phone', models.CharField(blank=True, help_text="Patient's contact phone number.", max_length=15, null=True)),
                ('lab_report_file', models.BinaryField(blank=True, help_text='The actual lab report file (bytea/BLOB data).', null=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='HospitalOwner',
            fields=[
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='owner', serialize=False, to='accounts.hospital')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('prescription_file', models.BinaryField(help_text='The actual prescription file (bytea/BLOB data).')),
                ('doctor_pin_lookup', models.BigIntegerField(help_text="The Doctor's unique PIN at the time of prescription.")),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='accounts.patient')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.patient', to_field='abha_id')),
                ('lab_report_file', models.BinaryField(help_text='The actual lab report file (bytea/BLOB data).')),
                ('category', models.TextField()),
                ('time', models.DateTimeField()),
                ('completed', models.BooleanField()),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_results', to='accounts.hospital')),
            ],
            options={
                'verbose_name': 'Lab Report',
                'verbose_name_plural': 'Lab Reports',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.TextField()),
                ('category', models.TextField()),
                ('booked_slot', models.BigIntegerField()),
                ('availability', models.BooleanField()),
                ('time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.doctor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.patient')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'unique_together': {('doctor', 'time', 'booked_slot')},
            },
        ),
    ]
